### ISSUE TITLE
var '_' is being used, so would be nicer if it actually got a proper name

### ISSUE THREAD

**Issue by SwissalpS** [The4codeblocks/compression_api#2]
`_` is normally used to indicate that a value is not being used. This is not a functional error, just a readability issue

https://github.com/The4codeblocks/compression_api/blob/cd8df800e653db3d730218746d98b343eac95898/init.lua#L15-L16

also, while I'm pointing out readability: putting spaces around operators helps a lot.
e.g. `for _=1,  count do` -> `for _ = 1, count do`, `x..y` -> `x .. y`, `x<y` -> `x < y` and `x+y` -> `x + y`

**Comment by The4codeblocks** [comment]
It used to be unused, I smushed the _ = 1 for that reason, now it's used, so.....
